# dbt_project.yml

# Name your project
name: 'my_new_project'
version: '1.0.0'
config-version: 2

# This setting specifies which profile dbt will use for this project
profile: 'default'

# Paths to various dbt folders
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directories for dbt to store compiled SQL files and clean up during `dbt clean`
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  my_new_project:                  # Change to match your project name if different
    staging_data_model:            # Model file name in the `models` directory
      +materialized: view          # Use "table" if you prefer a table instead of a view
